
title: Becca's Website
url: 'http://rapprl.github.io'
## baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Rebecca Rapp ## put your name
title: 'Graduate Student &amp; Physics Department'  ## your title
location: Pittsburgh, PA


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
instagram: http://www.instagram.com ## your instagram account url
## linkedin: http://www.linkedin.com  ## your linkedin account url
## dribbble: http://www.dribble.com  ## you dribbble account url
## foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
